from setuptools import setup

setup(
    name='iPeenCrawler',
    version='1.0 Alpha',
    packages=['venv.lib.python3.6.distutils', 'venv.lib.python3.6.encodings', 'venv.lib.python3.6.importlib',
              'venv.lib.python3.6.collections', 'venv.lib.python3.6.site-packages.bs4',
              'venv.lib.python3.6.site-packages.bs4.tests', 'venv.lib.python3.6.site-packages.bs4.builder',
              'venv.lib.python3.6.site-packages.pip', 'venv.lib.python3.6.site-packages.pip.req',
              'venv.lib.python3.6.site-packages.pip.vcs', 'venv.lib.python3.6.site-packages.pip.utils',
              'venv.lib.python3.6.site-packages.pip.compat', 'venv.lib.python3.6.site-packages.pip.models',
              'venv.lib.python3.6.site-packages.pip._vendor', 'venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip.commands', 'venv.lib.python3.6.site-packages.pip.operations',
              'venv.lib.python3.6.site-packages.idna', 'venv.lib.python3.6.site-packages.wheel',
              'venv.lib.python3.6.site-packages.wheel.tool', 'venv.lib.python3.6.site-packages.wheel.signatures',
              'venv.lib.python3.6.site-packages.certifi', 'venv.lib.python3.6.site-packages.chardet',
              'venv.lib.python3.6.site-packages.chardet.cli', 'venv.lib.python3.6.site-packages.pymysql',
              'venv.lib.python3.6.site-packages.pymysql.tests',
              'venv.lib.python3.6.site-packages.pymysql.tests.thirdparty',
              'venv.lib.python3.6.site-packages.pymysql.tests.thirdparty.test_MySQLdb',
              'venv.lib.python3.6.site-packages.pymysql.constants', 'venv.lib.python3.6.site-packages.urllib3',
              'venv.lib.python3.6.site-packages.urllib3.util', 'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.coverage', 'venv.lib.python3.6.site-packages.requests',
              'venv.lib.python3.6.site-packages.setuptools', 'venv.lib.python3.6.site-packages.setuptools.extern',
              'venv.lib.python3.6.site-packages.setuptools.command', 'venv.lib.python3.6.site-packages.sqlalchemy',
              'venv.lib.python3.6.site-packages.sqlalchemy.ext',
              'venv.lib.python3.6.site-packages.sqlalchemy.ext.declarative',
              'venv.lib.python3.6.site-packages.sqlalchemy.orm', 'venv.lib.python3.6.site-packages.sqlalchemy.sql',
              'venv.lib.python3.6.site-packages.sqlalchemy.util', 'venv.lib.python3.6.site-packages.sqlalchemy.event',
              'venv.lib.python3.6.site-packages.sqlalchemy.engine',
              'venv.lib.python3.6.site-packages.sqlalchemy.testing',
              'venv.lib.python3.6.site-packages.sqlalchemy.testing.suite',
              'venv.lib.python3.6.site-packages.sqlalchemy.testing.plugin',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.mssql',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.mysql',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.oracle',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.sqlite',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.sybase',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.firebird',
              'venv.lib.python3.6.site-packages.sqlalchemy.dialects.postgresql',
              'venv.lib.python3.6.site-packages.sqlalchemy.databases',
              'venv.lib.python3.6.site-packages.sqlalchemy.connectors',
              'venv.lib.python3.6.site-packages.pkg_resources', 'venv.lib.python3.6.site-packages.pkg_resources.extern',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor.packaging'],
    url='https://github.com/2017SeniorProject/iPeenCrawler',
    license='MIT',
    author='Mingtse Chen',
    author_email='gene31105@gmail.com',
    description='iPeen crawler to fetch ipeen restaurant data'
)
